---
- name: Create flask server
  hosts: webservers

  tasks:
  # - name: Log into private registry and force re-authorization
  #   docker_login:
  #     # registry: registry.hub.docker.com
  #     username: "{{DOCKER_USR}}"
  #     password: "{{DOCKER_PSW}}"
  #     reauthorize: yes
  - name: unlock session
    shell:
      security unlock-keychain -p {{sys_pwd}}
  
  - name: "create the file"
    shell:
      echo "First Line" > cat > /Users/dhanababu/training/todo/example.txt
      echo "First Line" > cat >> /Users/dhanababu/training/todo/example.txt

  - name: Start a container
    docker_container:
      name: "{{CONTAINER}}"
      image: "{{DOCKER_IMAGE}}"
      state: started
      restart: yes
      ports:
      - "9000:5000"
      volumes:
      - "/Users/dhanababu/training/todo/:/todo-db/"