---
- name: Create flask server
  hosts: webservers

  tasks:
  - name: Log into private registry and force re-authorization
    docker_login:
      # registry: registry.hub.docker.com
      username: "{{DOCKER_USR}}"
      password: "{{DOCKER_PSW}}"
      reauthorize: yes

  - name: Start a container
    docker_container:
      name: "{{CONTAINER}}"
      image: "{{DOCKER_IMAGE}}"
      state: started
      restart: yes
      ports:
      - "5000:5000"
